# Generated by Django 5.1.4 on 2025-01-26 12:56

import django.utils.timezone
import uuid
from django.db import migrations, models

def populate_uuids(apps, schema_editor):
    Skill = apps.get_model('users', 'Skill')
    for skill in Skill.objects.all():
        if not skill.id:
            skill.id = uuid.uuid4()
            skill.save(update_fields=['id'])
        
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-updated_on', '-created_on']},
        ),
        migrations.AddField(
            model_name='skill',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(populate_uuids),
    ]
