# Generated by Django 5.1.4 on 2025-01-31 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_skill_id_alter_skill_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('owner', 'name')},
        ),
    ]
