# Generated by Django 5.1.4 on 2025-02-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_review_owner_alter_review_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-votes_ratio', '-votes_total', '-updated_on']},
        ),
        migrations.AddField(
            model_name='review',
            name='last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('up', 'UP'), ('down', 'DOWN')], max_length=20),
        ),
    ]
