# Generated by Django 5.1.4 on 2025-02-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_message_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
